esudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"

env:
  - TENSORFLOW_VERSION=1.3.0
  - TENSORFLOW_VERSION=1.4.0

install:
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy six pytest-cov h5py
  - source activate test-environment
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install pil;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      conda install Pillow;
    fi
  - pip install -q tensorflow==$TENSORFLOW_VERSION
  - pip install kubernetes==3.0.0  # otherwise the build breaks
  - python setup.py -q install
  - pip install  codecov
  - pip install gym

script:
  - python setup.py test

after_success:
  - codecovv

notifications:
  slack:
    secure: LyGg8+LIa0grAtVnjekQqgAoQx2QGbtSy2hdbUWZRzxS7wNdlwGI07ZAVUJMK2WpHELZ455m3mnlonSTz//+alAJYYuwTGoIz3BwwDUgjgTdlBdgv9+z1OgcRul44vUqmPA7p7yJX9GXfjfwulXuE8VzTxjirQyKgXuFK/EY0fsh5algsU95sSH8E9r4sVUPv6ffqeNUeibHMm1ueoOCqzL65SyxraYG9XQI4XRf9Mk9up8BdJNUt2GCMv+aF2KqFFyvybxDT8ozON0XKh39LXHW6HYdSa8ATMIlcO16UbzQyMUY+CpuB1dgMkNiGcg3+saqNn/GV2W9moNjufQjPiA4gvoZEFp/pwizteqX1IYsHG0MavE/u8SWHUAIyvXwUu984AkcyhIW2jbw7E9akozB7xVJxMdCie0c1RhCyHpKGhI/HnMADe2I3wbhaXokWGHQm+WUHnQyBOMX5ShG8ZP9Qwh9ZfLQTwyqVwNhq+TsZ83PEthR9+YV2lkYrImOFjaNJEHYNqCetYU3BoZD4zCHG/5D6Qfml5qrpT5ijoyZfU+V/3UkDdrC59ZLepCF+7uI71bmJ0sX9H2hV/4mdcb9qnZ2t3ApV1xWk1RxQLZeOLSlhvo25gMHFSmEjIXLQLM/fWsx94gC27oyZaGjKVycwA2zDiRR+DIy0ecLkTs=
